-- Insert sample products with proper UUIDs
INSERT INTO products (
    id,
    name,
    description,
    price,
    rating,
    popularity,
    discount,
    vendor,
    image,
    category_id,
    tags,
    affiliate_type,
    affiliate_link
) VALUES 
(
    gen_random_uuid(),
    'Premium Grain-Free Dog Food',
    'All-natural, grain-free formula for optimal nutrition. Made with real meat and wholesome ingredients.',
    59.99,
    4.8,
    95,
    10,
    'PawNatural',
    'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?auto=format&fit=crop&w=1074&q=80',
    'food',
    ARRAY['grain-free', 'natural', 'premium'],
    'amazon',
    'B0D4TVG78S'
),
(
    gen_random_uuid(),
    'Interactive Puzzle Toy',
    'Mental stimulation toy for intelligent play. Keeps your dog entertained and challenged.',
    24.99,
    4.6,
    88,
    15,
    'SmartPup',
    'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&w=1074&q=80',
    'toys',
    ARRAY['interactive', 'puzzle', 'mental-stimulation'],
    'amazon',
    'B081TN3MV6'
),
(
    gen_random_uuid(),
    'Orthopedic Memory Foam Bed',
    'Therapeutic bed for optimal joint support. Perfect for senior dogs or those with joint issues.',
    89.99,
    4.9,
    92,
    20,
    'ComfortPets',
    'https://images.unsplash.com/photo-1591946614720-90a587da4a36?auto=format&fit=crop&w=1074&q=80',
    'bedding',
    ARRAY['orthopedic', 'memory-foam', 'therapeutic'],
    'amazon',
    'B07F3DTXQD'
),
(
    gen_random_uuid(),
    'Natural Dog Shampoo',
    'Gentle, all-natural shampoo for sensitive skin. Made with organic ingredients.',
    19.99,
    4.7,
    85,
    0,
    'PawCare',
    'https://images.unsplash.com/photo-1581888227599-779811939961?auto=format&fit=crop&w=1074&q=80',
    'grooming',
    ARRAY['natural', 'sensitive-skin', 'organic'],
    'amazon',
    'B08F7N1L3K'
),
(
    gen_random_uuid(),
    'Professional Dog Training Kit',
    'Complete training kit with clicker, treats pouch, and training guide.',
    34.99,
    4.5,
    78,
    25,
    'TrainPro',
    'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=1074&q=80',
    'training',
    ARRAY['training', 'professional', 'kit'],
    'amazon',
    'B093WTRM8N'
);